language: go
go:
- 1.14.x
env:
  - GO111MODULE=on
install:
- go get -v
before_deploy: make build-all
deploy:
  provider: releases
  api_key: PikvhD0CQV1voD6PE+DRdQFiav6kPPbEVHlyDKu0AaYzq4YhnBn6X7brJ6q7R7O5nVReQOnmrnEtizf5s8EBmoNFzBThgAWDwrQ48/AFVAVFaYLMSXh3mfwsOg97UOE/41+LAzabmuX3KWkcprLKWZt0sINKdaVRn8kbvFgSG60rbjz9eo5eKDyhOXBA8wntmb+eqz2rJoJcTzhfek77R0HuoGc3x3Du6YZ9sP6cooV40cCQjTdhHeqMouUu/U9kkU2jN0s4cHKowDvl6g1jNhVce6j5k9RXLi169WjsLfuv9d0fZ+M828yE5Oa7+mVQFvI+tvMZZgfcHAsVjlhbmHI4Fvc1Br0607Ql+Z4ZnHjfLjEfCq2P04SL8y2ZWuMQ3UEC0Ry1VtHSnMxQSk9pOT6OuwaXlpuP/J1DZ5jQJpxazOusNPCNas9qbxaEqM7JVucptlOiVJlMVbW9l7hIQZC99de3d7YKZhQrFLfR7Xu3QNwcZ4ci9oNS92K95PML0WfROvUB96pCRD51UDJW3wh2buz7jF42jpmrq6qRIVjg/apC1x2Go4bg3nHXI5MOvwxaa0iplyFF2Edx4ruhKEKKO9GTvIbnnUooTCD/N47irD5VYgsEF74xcTIGtOzAcis960jo8aGFQCzK+UifjAAk1qZLwqveElIp1d/yelI=
  file_glob: true
  file: bin/*
  skip_cleanup: true
  on:
    repo: edboffical/webdog
    tags: true
